// Mocks generated by Mockito 5.3.2 from annotations
// in tv_series/test/presentation/pages/search_tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/usecases/search_tv_series.dart' as _i2;
import 'package:tv_series/presentation/bloc/search/search_cubit.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchTvSeries_0 extends _i1.SmartFake
    implements _i2.SearchTvSeries {
  _FakeSearchTvSeries_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchTvSeriesState_1 extends _i1.SmartFake
    implements _i3.SearchTvSeriesState {
  _FakeSearchTvSeriesState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvSeriesCubit extends _i1.Mock
    implements _i3.SearchTvSeriesCubit {
  @override
  _i2.SearchTvSeries get searchTvSeries => (super.noSuchMethod(
        Invocation.getter(#searchTvSeries),
        returnValue: _FakeSearchTvSeries_0(
          this,
          Invocation.getter(#searchTvSeries),
        ),
        returnValueForMissingStub: _FakeSearchTvSeries_0(
          this,
          Invocation.getter(#searchTvSeries),
        ),
      ) as _i2.SearchTvSeries);
  @override
  _i3.SearchTvSeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSearchTvSeriesState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSearchTvSeriesState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.SearchTvSeriesState);
  @override
  _i4.Stream<_i3.SearchTvSeriesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i3.SearchTvSeriesState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i3.SearchTvSeriesState>.empty(),
      ) as _i4.Stream<_i3.SearchTvSeriesState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i4.Future<void> resultData(String? query) => (super.noSuchMethod(
        Invocation.method(
          #resultData,
          [query],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void emit(_i3.SearchTvSeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i5.Change<_i3.SearchTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
