// Mocks generated by Mockito 5.3.2 from annotations
// in tv_series/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:flutter_bloc/flutter_bloc.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/entities/tv_series_detail.dart' as _i13;
import 'package:tv_series/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:tv_series/domain/usecases/get_tv_series_recommendations.dart'
    as _i4;
import 'package:tv_series/domain/usecases/get_watchlist_tv_series.dart' as _i6;
import 'package:tv_series/domain/usecases/get_watchlist_tv_series_status.dart'
    as _i7;
import 'package:tv_series/domain/usecases/remove_watchlist_tv_series.dart'
    as _i9;
import 'package:tv_series/domain/usecases/save_watchlist_tv_series.dart' as _i8;
import 'package:tv_series/presentation/bloc/detail/detail_cubit.dart' as _i3;
import 'package:tv_series/presentation/bloc/recommendation/recommendation_cubit.dart'
    as _i5;
import 'package:tv_series/presentation/bloc/watchlist/watchlist_cubit.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTvSeriesDetail {
  _FakeGetTvSeriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDetailTvSeriesState_1 extends _i1.SmartFake
    implements _i3.DetailTvSeriesState {
  _FakeDetailTvSeriesState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesRecommendations_2 extends _i1.SmartFake
    implements _i4.GetTvSeriesRecommendations {
  _FakeGetTvSeriesRecommendations_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRecommendationTvSeriesState_3 extends _i1.SmartFake
    implements _i5.RecommendationTvSeriesState {
  _FakeRecommendationTvSeriesState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTvSeries_4 extends _i1.SmartFake
    implements _i6.GetWatchlistTvSeries {
  _FakeGetWatchlistTvSeries_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListTvSeriesStatus_5 extends _i1.SmartFake
    implements _i7.GetWatchListTvSeriesStatus {
  _FakeGetWatchListTvSeriesStatus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTvSeries_6 extends _i1.SmartFake
    implements _i8.SaveWatchlistTvSeries {
  _FakeSaveWatchlistTvSeries_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTvSeries_7 extends _i1.SmartFake
    implements _i9.RemoveWatchlistTvSeries {
  _FakeRemoveWatchlistTvSeries_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchlistTvSeriesState_8 extends _i1.SmartFake
    implements _i10.WatchlistTvSeriesState {
  _FakeWatchlistTvSeriesState_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DetailTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailTvSeriesCubit extends _i1.Mock
    implements _i3.DetailTvSeriesCubit {
  @override
  _i2.GetTvSeriesDetail get detailTvSeries => (super.noSuchMethod(
        Invocation.getter(#detailTvSeries),
        returnValue: _FakeGetTvSeriesDetail_0(
          this,
          Invocation.getter(#detailTvSeries),
        ),
        returnValueForMissingStub: _FakeGetTvSeriesDetail_0(
          this,
          Invocation.getter(#detailTvSeries),
        ),
      ) as _i2.GetTvSeriesDetail);
  @override
  _i3.DetailTvSeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDetailTvSeriesState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDetailTvSeriesState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.DetailTvSeriesState);
  @override
  _i11.Stream<_i3.DetailTvSeriesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i3.DetailTvSeriesState>.empty(),
        returnValueForMissingStub: _i11.Stream<_i3.DetailTvSeriesState>.empty(),
      ) as _i11.Stream<_i3.DetailTvSeriesState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i11.Future<void> getDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getDetail,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void emit(_i3.DetailTvSeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i12.Change<_i3.DetailTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [RecommendationTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationTvSeriesCubit extends _i1.Mock
    implements _i5.RecommendationTvSeriesCubit {
  @override
  _i4.GetTvSeriesRecommendations get recommendationTvSeries =>
      (super.noSuchMethod(
        Invocation.getter(#recommendationTvSeries),
        returnValue: _FakeGetTvSeriesRecommendations_2(
          this,
          Invocation.getter(#recommendationTvSeries),
        ),
        returnValueForMissingStub: _FakeGetTvSeriesRecommendations_2(
          this,
          Invocation.getter(#recommendationTvSeries),
        ),
      ) as _i4.GetTvSeriesRecommendations);
  @override
  _i5.RecommendationTvSeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeRecommendationTvSeriesState_3(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeRecommendationTvSeriesState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.RecommendationTvSeriesState);
  @override
  _i11.Stream<_i5.RecommendationTvSeriesState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i5.RecommendationTvSeriesState>.empty(),
        returnValueForMissingStub:
            _i11.Stream<_i5.RecommendationTvSeriesState>.empty(),
      ) as _i11.Stream<_i5.RecommendationTvSeriesState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i11.Future<void> getData(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void emit(_i5.RecommendationTvSeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i12.Change<_i5.RecommendationTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [WatchlistTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvSeriesCubit extends _i1.Mock
    implements _i10.WatchlistTvSeriesCubit {
  @override
  _i6.GetWatchlistTvSeries get getWatchlistTvSeries => (super.noSuchMethod(
        Invocation.getter(#getWatchlistTvSeries),
        returnValue: _FakeGetWatchlistTvSeries_4(
          this,
          Invocation.getter(#getWatchlistTvSeries),
        ),
        returnValueForMissingStub: _FakeGetWatchlistTvSeries_4(
          this,
          Invocation.getter(#getWatchlistTvSeries),
        ),
      ) as _i6.GetWatchlistTvSeries);
  @override
  _i7.GetWatchListTvSeriesStatus get getWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetWatchListTvSeriesStatus_5(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
        returnValueForMissingStub: _FakeGetWatchListTvSeriesStatus_5(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i7.GetWatchListTvSeriesStatus);
  @override
  _i8.SaveWatchlistTvSeries get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveWatchlistTvSeries_6(
          this,
          Invocation.getter(#saveWatchlist),
        ),
        returnValueForMissingStub: _FakeSaveWatchlistTvSeries_6(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i8.SaveWatchlistTvSeries);
  @override
  _i9.RemoveWatchlistTvSeries get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveWatchlistTvSeries_7(
          this,
          Invocation.getter(#removeWatchlist),
        ),
        returnValueForMissingStub: _FakeRemoveWatchlistTvSeries_7(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i9.RemoveWatchlistTvSeries);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set message(String? _message) => super.noSuchMethod(
        Invocation.setter(
          #message,
          _message,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.WatchlistTvSeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWatchlistTvSeriesState_8(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeWatchlistTvSeriesState_8(
          this,
          Invocation.getter(#state),
        ),
      ) as _i10.WatchlistTvSeriesState);
  @override
  _i11.Stream<_i10.WatchlistTvSeriesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i10.WatchlistTvSeriesState>.empty(),
        returnValueForMissingStub:
            _i11.Stream<_i10.WatchlistTvSeriesState>.empty(),
      ) as _i11.Stream<_i10.WatchlistTvSeriesState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i11.Future<void> getDataWatchlist() => (super.noSuchMethod(
        Invocation.method(
          #getDataWatchlist,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> getStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> addToWatchlist(_i13.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToWatchlist,
          [tvSeries],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i13.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvSeries],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void emit(_i10.WatchlistTvSeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i12.Change<_i10.WatchlistTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}
