// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQkdvSB2l9b98cbRyksQ_48BLrMiljKk',
    appId: '1:601909712401:web:c3b5b076242d27a6fc83b0',
    messagingSenderId: '601909712401',
    projectId: 'ditonton-1a45e',
    authDomain: 'ditonton-1a45e.firebaseapp.com',
    storageBucket: 'ditonton-1a45e.appspot.com',
    measurementId: 'G-BTK2JKMBZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyC6ms62t-nkRc0G_Mr1d35Mj8wEQtPcU',
    appId: '1:601909712401:android:4d8dba570536a048fc83b0',
    messagingSenderId: '601909712401',
    projectId: 'ditonton-1a45e',
    storageBucket: 'ditonton-1a45e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGsGB8pKw0SA2pDxCAhmdtj6zUZ4gj3M',
    appId: '1:601909712401:ios:b50dc0dc569dcdc6fc83b0',
    messagingSenderId: '601909712401',
    projectId: 'ditonton-1a45e',
    storageBucket: 'ditonton-1a45e.appspot.com',
    iosClientId: '601909712401-7ugat048i5vd833rup4et6bv7s6mokjg.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
